# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: What? Like it's hard?
email: jennette.reid@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bibliophile, Software Testing Monkey, Mother, Maker of Banana Hammocks, Lover of Bunnies, Aspiring Planeteer. 

  Masters of the Universe haters need not apply.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jennetters.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jennetters
linkedin_username: jennette-reid
twitter_username: jennetters
instagram_username: jennettereid

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: gray
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/